#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

# Stand-in for cargo: '--version', 'locate-project' and
# 'generate-lockfile', the only commands rust-audit.sh runs. Each call
# must carry exactly the expected arguments; it is recorded with its
# working directory and the environment it sees (record.sh).

set -euo pipefail
# shellcheck source=record.sh
source "$(dirname -- "${BASH_SOURCE[0]}")/record.sh"

record() {
  record_call "$MOCK_TOOL_LOG" "$1"
}

expect_args() {
  local -a expected=("$@")
  local i
  if [ "${#actual[@]}" -ne "${#expected[@]}" ]; then
    echo "cargo stand-in: unexpected arguments: ${actual[*]}" >&2
    exit 90
  fi
  for i in "${!expected[@]}"; do
    if [ "${actual[$i]}" != "${expected[$i]}" ]; then
      echo "cargo stand-in: unexpected arguments: ${actual[*]}" >&2
      exit 90
    fi
  done
}

workspace_manifest="${MOCK_WORKSPACE_MANIFEST:-$MOCK_EXPECT_MANIFEST}"
actual=("$@")
case "${1:-}" in
  --version)
    record cargo-version
    echo "cargo ${MOCK_CARGO_VERSION:-1.99.0} (5f94df478 2026-08-27)"
    ;;
  locate-project)
    record locate-project
    expect_args locate-project --workspace --locked \
      --manifest-path "$MOCK_EXPECT_MANIFEST" --message-format plain
    if [ "${MOCK_LOCATE_FAIL:-false}" = "true" ]; then
      echo "error: could not find Cargo.toml" >&2
      exit 101
    fi
    printf '%s\n' "${MOCK_LOCATE_OUTPUT:-$workspace_manifest}"
    ;;
  generate-lockfile)
    record generate-lockfile
    expect_args generate-lockfile --manifest-path "$workspace_manifest"
    if [ "${MOCK_GENERATE_FAIL:-false}" = "true" ]; then
      printf '%s\n' "${MOCK_GENERATE_STDOUT:-}"
      echo "error: failed to select a version" >&2
      exit 101
    fi
    echo "    Locking 1 package to latest compatible version" >&2
    if [ -n "${MOCK_GENERATE_STDOUT:-}" ]; then
      printf '%s\n' "$MOCK_GENERATE_STDOUT"
    fi
    printf '# Generated by the cargo stand-in\nversion = 4\n' \
      > "$(dirname -- "$workspace_manifest")/Cargo.lock"
    ;;
  *)
    echo "cargo stand-in: unexpected command: ${1:-}" >&2
    exit 90
    ;;
esac
